about: >
  This file describes all the numeric parameters for the model. All values
  are assumed to be floats unless otherwise specified, and have the given
  range and precision values.
  
  The order of sections in the interface is the same as the order that they
  are first listed here.

initial_help: >
  Welcome to WebDICE. This informational help box will describe, in a few
  words, how to use this model and understand its output. It will disappear,
  however, after you create a model run, to avoid cluttering your workspace.
  
  To begin, click "Make New Run" to the left to create a run with default
  parameters.
  
  This message is unhelpful. To edit it, please change the relevant lines
  in parameters.yaml.

advanced_help: >
  ## WebDICE Documentation
  
  This block of text is primarily to explain the rationale behind all
  the various parameters in WebDICE as well as explain more about the
  internal processes of the model.
  
  Here is the quadratic formula:
  
  \[
  x = \frac{-b \pm \sqrt{b^2 - 4ac}}{2a}
  \]
  
  And here is the equation for the identity matrix: $$I_{x,y} = \delta_{xy}$$
  
  Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
  
  # A Tower of Many Headings
  
  Some text.
  
  ## A Tower of Many Headings
  
  Some text.
  
  ### A Tower of Many Headings
  
  Some text.
  
  #### A Tower of Many Headings
  
  Some text.
  
  ##### A Tower of Many Headings
  
  Some text.
  
  Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim
  veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex
  ea commodo consequat. Duis aute irure dolor in reprehenderit in
  voluptate velit esse cillum dolore eu fugiat nulla pariatur. 
  Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia
  deserunt mollit anim id est laborum.
  
  Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim
  veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea
  commodo consequat. Duis aute irure dolor in reprehenderit in voluptate
  velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint
  occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit
  anim id est laborum.

last_modified: 5 July 2012 

parameters:
  - name: Climate Sensitivity
    machine_name: t2xco2
    section: Model Parameters
    min: 1
    max: 7
    step: 0.5
    default: 3
    description: n/a
  - name: Environment Damages
    machine_name: a3
    section: Model Parameters
    min: 1
    max: 3
    step: 0.5
    default: 2
    description: n/a
  - name: Technology Growth
    machine_name: technology
    section: Model Parameters
    min: 0.05
    max: 0.15
    step: 0.05
    default: 0.1
    description: n/a
  - name: Consumption Elasticity  
    section: Advanced Parameters
    machine_name: elasmu
    min: 1
    default: 2
    max: 3
    step: 0.1
  - name: Time Preference Rate
    section: Advanced Parameters
    machine_name: prstp
    min: 0
    default: 0.015
    max: 4
    step: 0.005
  - name: Savings Rate
    section: Advanced Parameters
    machine_name: savings
    default: 0.2
    min: 0.15
    max: 0.25
    step: 0.05
  - name: Max Population
    section: Advanced Parameters
    machine_name: popasym
    min: 8000
    max: 12000
    step: 2000
    default: 8600
  - name: Capital Depreciation
    section: Advanced Parameters
    machine_name: dk
    default: 0.1
    min: 0.08
    max: 0.2
    step: 0.01
  - name: Carbon Reduction
    section: Advanced Parameters
    machine_name: dsig
    default: 0.003
    min: 0
    max: 0.06
    step: 0.001
  - name: Doubling Damage
    section: CO_(2) Controls
    machine_name: a2
    default: 0.0028 # 388
    min:  0.002
    max:  0.0035
    step: 0.0001
  - name: Cost
    section: Abatement
    machine_name: expcost2
    default: 2.8
    min: 2
    max: 4
    step: 0.1
  - name: Decline Rate of Cost
    section: Abatement
    machine_name: gback
    default: 0.05
    min: 0
    max: 0.2
    step: 0.05
  - name: Fossil Fuel Reserves
    section: CO_(2) Controls
    machine_name: fosslim
    min: 6000
    max: 9000
    step: 500
    default: 6000
  - name: Emissions by 2050
    machine_name: e2050
    section: Carbon Policy
    min: 0.00
    max: 1.00
    step: 0.10
    default: 0.00
  - name: Emissions by 2100
    machine_name: e2100
    section: Carbon Policy
    min: 0.00
    max: 1.00
    step: 0.10
    default: 0.00
  - name: Emissions by 2150
    machine_name: e2150
    section: Carbon Policy
    min: 0.00
    max: 1.00
    step: 0.10
    default: 0.00
  - name: Oceanic Model
    machine_name: oceanmodel
    section: Model Design 
    values:
      - name: DICE
        machine_name: dice
        description: n/a
      - name: Glotter
        machine_name: glotter
        description: n/a
  - name: Damages Model
    machine_name: damages_model
    section: Model Design
    values:
      - name: DICE Damages to Gross Output
        machine_name: dice
        description: n/a
      - name: Kopp Damages to Capital
        machine_name: kopp
        description: n/a
      - name: Damages to Productivity
        machine_name: productivity
        description: n/a

measurements:
  - name: Atmospheric Temperature Increase
    machine_name: tempAtmosphere
    unit: °C from 1900
    description: n/a
  - name: Income per Capita
    machine_name: consumptionpercapita
    unit: per Person
    description: n/a
    format: "$#.##"
  - name: Carbon Mass in Atmosphere
    machine_name: massAtmosphere
    unit: Gt of Carbon
    description: n/a
  - name: Total Emissions per Year
    machine_name: emissionsTotal
    unit: Gt Carbon / 10 yr
    description: n/a