about: >
  This file describes all the numeric parameters for the model. All values
  are assumed to be floats unless otherwise specified, and have the given
  range and precision values.
  
  The order of sections in the interface is the same as the order that they
  are first listed here.

initial_help: >
  Welcome to WebDICE. This informational help box will describe, in a few
  words, how to use this model and understand its output. It will disappear,
  however, after you create a model run, to avoid cluttering your workspace.
  
  To begin, click "Make New Run" to the left to create a run with default
  parameters.

last_modified: 5 July 2012 

parameters:
  - name: Climate Sensitivity
    machine_name: t2xco2
    section: Model Parameters
    min: 1
    max: 7
    step: 0.5
    default: 3
    description: n/a
  - name: Environment Damages
    machine_name: a3
    section: Model Parameters
    min: 1
    max: 3
    step: 0.5
    default: 2
    description: n/a
  - name: Population Growth
    machine_name: gpop0
    section: Model Parameters
    min: 0.1
    max: 0.5
    step: 0.05
    default: 0.35
    description: n/a
  - name: Technology Growth
    machine_name: technology
    section: Model Parameters
    min: 0.05
    max: 0.15
    step: 0.05
    default: 0.1
    description: n/a
  - name: Emissions by 2050
    machine_name: e2050
    section: Carbon Controls
    min: 0.00
    max: 1.00
    step: 0.10
    default: 0.00
  - name: Emissions by 2100
    machine_name: e2100
    section: Carbon Controls
    min: 0.00
    max: 1.00
    step: 0.10
    default: 0.00
  - name: Emissions by 2150
    machine_name: e2150
    section: Carbon Controls
    min: 0.00
    max: 1.00
    step: 0.10
    default: 0.00
  - name: Oceanic Model
    machine_name: oceanmodel
    section: Model Design 
    values:
      - name: DICE
        machine_name: dice
        description: n/a
      - name: Glotter
        machine_name: glotter
        description: n/a
  - name: Damages Model
    machine_name: damages_model
    section: Model Design
    values:
      - name: DICE Damages to Gross Output
        machine_name: dice
        description: n/a
      - name: Kopp Damages to Capital
        machine_name: kopp
        description: n/a
      - name: Damages to Productivity
        machine_name: productivity
        description: n/a

measurements:
  - name: Carbon Mass in Atmosphere
    machine_name: massAtmosphere
    unit: Gt of Carbon
    description: n/a
  - name: Atmospheric Temperature Increase
    machine_name: tempAtmosphere
    unit: °C from 1900
    description: n/a
  - name: Per Capita Consumption
    machine_name: consumptionpercapita
    unit: per Person
    description: n/a
    format: "$#.##"
  - name: Total Emissions
    machine_name: emissionsTotal
    unit: Gt Carbon / 10 yr
    description: n/a