about: >
  This file describes all the numeric parameters for the model. All values
  are assumed to be floats unless otherwise specified, and have the given
  range and precision values.

  The order of sections in the interface is the same as the order that they
  are first listed here.

  This is a file that allows the programmer to change what is on the interface of the website
  without having to edit the actual code. It works by having a heirarchy of arrays that
  are passed to index.php. The order is configuration:header:entry:attribute(data about attribute).
  For example, configuration['parameters'] would contain everything under "parameters:"
  in the yaml file. parameters is itself an array of entries. Each new entry begins with a " -  "
  Each attribute below the entry (in the form attrbute:data) is stored together with the other
  entry data. This allows you to iterate through each parameter and take its data, such as "min",
  "max", and "default", and generate a range slider in the php code using that data. Attributes such as
  "tab" and "section" define where each entry will go. Tabs and such are autogenerated when index.php runs,
  so it creates what ever tabs the programmer has named in this yaml file.

  This file is set up to make it easy to add new things. Some just need text, like the intital_help below.
  Some need entries, subentries, and data. All you have to do is type in what you need, and it will
  Be findable in index.php under configuration['header'] and any subarrays beneath that.

  Sorry if that explanation was too convoluted. Basically, all this file does is store data. What happens
  to that data is completely determined by the index.php file.

  Indentation is extremely important in this yaml file. Anything indented by two spaces is assumed
  to be "under" whatever is above it. Not indenting by two spaces makes the yaml reader think it is
  something new.


initial_help:
  index: >
      webDICE is a simulation tool designed to show how climate change might affect
      people living today and in the future. It is based in the most widely used
      model of the economy and the climate, the DICE model, developed by Professor
      William Nordhaus, of Yale University. webDICE allows you to run the DICE
      model quickly with an easy to use interface. You can change the key variables
      in the model to reflect your views about the economy and about climate change
      and run the model with these choices.

      The complete set of DICE variables can be found in the “Advanced” version.
      An abbreviated set of variables is available in the “Basic” version.

      The model has been developed by researchers at the University of Chicago
      supported by RDCEP. We are continually working to improve the model and the
      interface. If you have suggestions, contact us at
      <a href="mailto:info-rdcep@ci.uchicago.edu" target="_blank">info-rdcep@ci.uchicago.edu</a>.


  advanced: >
      To run a simulation click on the “Run Model” button at the bottom of the
      page. The variables are set to the defaults based on our best guess of the
      correct values. You can change the variables to reflect your views by moving
      the sliders. Running a simulation will let you see how the outcomes change.


  basic: >
      To run a simulation click on the “Run Model” button at the bottom of the
      page. The variables are set to the defaults based on our best guess of the
      correct values. You can change the variables to reflect your views by moving
      the sliders. Running a simulation will let you see how the outcomes change.


tabs:
  - name: Policy
    sections:
      - name: Business as usual
        machine_name: default
        radio: true
      - name: Simulated carbon tax
        machine_name: carbon_tax
        radio: true
        min: 0
        max: 500
        default: 0
        step: 10
        precision: 0
        unit: '$/t'
        parameters:
          - name: 2050
            machine_name: c2050
          - name: 2100
            machine_name: c2100
          - name: 2150
            machine_name: c2150
      - name: Simulated climate treaty
        machine_name: treaty
        radio: true
      - name: 'Limitations on emissions (as a percent of 2005 emissions)'
        min: 0
        max: 100
        step: 5
        default: 0
        precision: 0
        unit: '%'
        parameters:
          - name: 2050
            machine_name: e2050
            section:
            description: The mandated decrease in emissions by 2050 as a share of 2005 year emissions.
          - name: 2100
            machine_name: e2100
            description: The mandated decrease in emissions by 2100 as a share of 2005 year emissions.
          - name: 2150
            machine_name: e2150
            description: The mandated decrease in emissions by 2150 as a share of 2005 year emissions.
      - name: Participation
        min: 0
        max: 100
        step: 10
        default: 100
        precision: 0
        unit: '%'
        parameters:
          - name: 2050
            machine_name: p2050
            description: Participation in the climate treaty by 2050.
          - name: 2100
            machine_name: p2100
            description: Participation in the climate treaty by 2100.
          - name: 2150
            machine_name: p2150
            description: Participation in the climate treaty by 2150.
      - name: Optimized policy
        machine_name: optimized
        radio: true
  - name: Climate
    sections:
      - name: Your beliefs about the climate and the future
        parameters:
          - name: 'Climate sensitivity: How much will temperatures go up?'
            machine_name: t2xco2
            min: 1
            max: 5
            step: 0.5
            default: 3.0
            precision: 1
            description: Temperature increase in degrees C from doubling of atmospheric CO2
            unit: °C
          - name: How large will the harms be?
            machine_name: a3
            min: 1
            max: 4
            step: 0.5
            default: 2.0
            precision: 1
            description: Increase in harms from climate change due to an increase in temperatures
      - name: Model design
        parameters:
          - name: Carbon cycle
            machine_name: carbon_model
            description: Oceanic model of carbon transfer
            disabled: true
            options:
              - name: DICE
                machine_name: dice_carbon
          - name: Damages model
            machine_name: damages_model
            description: Way that climate change harms enter the economy
            options:
              - name: DICE Damages to Gross Output
                machine_name: dice
              - name: Exponential mapping to output
                machine_name: exponential
              - name: Additive to output
                machine_name: additive
              - name: Weitzman tipping point
                machine_name: tipping_point
              - name: Fraction of productivity
                machine_name: productivity
        #      - name: Kopp Damages to Capital
        #        machine_name: kopp
        #        description: Climate change destroys a certain percentage of global input
        #      - name: Damages to Productivity
        #        machine_name: productivity
        #        description: Climate change reduces the rate of growth in global productivity
  - name: Economy
    sections:
      - name: Cost of reducing emissions
        parameters:
          - name: Marginal cost of reducing emissions
            machine_name: expcost2
            default: 2.8
            min: 2
            max: 4
            step: 0.1
            precision: 1
            description: Additional cost from more abatement
          - name: How fast will the costs of renewable energy decline?
            machine_name: gback
            default: 0.05
            min: 0
            max: 0.2
            step: 0.05
            precision: 2
            description: Rate of decline in costs of reduction emissions
            unit: "%"
          - name: How low will the costs of renewables go?
            machine_name: backrat
            default: 2.0
            min: 1.0
            max: 4
            step: 0.5
            precision: 1
            description: Cost of replacing all emissions in 2012 $ per ton of CO_{2} , relative to future cost
      - name: Econommic performance
        parameters:
          - name: Decline in rate of growth of productivity
            machine_name: dela
            min: 0.05
            max: 1.5
            step: 0.05
            default: 0.10
            precision: 2
            description: Decline in the rate of growth in productivity over time
            unit: '%'
          - name: Depreciation rate
            machine_name: dk
            default: 0.10
            min: 0.08
            max: 0.2
            step: 0.01
            precision: 2
            description: Rate of depreciation per year
            unit: '%'
          - name: Savings rate
            machine_name: savings
            default: 0.2
            min: 0.15
            max: 0.25
            step: 0.05
            precision: 2
            description: Savings are per year
            unit: '%'
          - name: Max population
            tab: Advanced
            section: Additional Parameters
            machine_name: popasym
            min: 8000
            max: 12000
            step: 200
            default: 8600
            precision: 0
            description: Number, in millions, that the population grows asymptotically towards
            unit: ' billions'
      - name: Energy parameters
        parameters:
          - name: Change in energy intensity
            machine_name: dsig
            default: 0.3
            min: 0.0
            max: 6.0
            step: 0.1
            precision: 1
            description: Rate of decline in energy use per $ of GDP
            unit: '%'
          - name: Fossil fuel reserves
            tab: Advanced
            section: Additional Parameters
            machine_name: fosslim
            min: 6000
            max: 9000
            step: 500
            default: 6000
            precision: 0
            description: Fossil fuels remaining, measured in CO2 emissions
            unit: ' Gt&nbsp;C'
      - name: Utility parameters
        parameters:
          - name: Elasticity of marg. consump.
            machine_name: elasmu
            min: 1
            default: 2.0
            max: 3
            step: 0.1
            precision: 1
            description: Exponent of consumption in utility function
          - name: Pure rate of time preference
            machine_name: prstp
            min: 0
            default: 0.015
            max: .1
            step: 0.005
            precision: 3
            description: Discount rate applied to utility


measurements:
  - name: User-controlled Inputs
    options:
      - name: Total Factor Productivity
        machine_name: al
      - name: Clean Energy Costs
        machine_name: backstop
        unit: Thousands $USD / ton of CO2
      - name: Carbon Intensity
        machine_name: sigma
        unit: tons of CO2 / 1000 $USD
      - name: Labor Supply
        machine_name: l
        unit: Millions
  - name: Economic Results
    options:
      - name: Consumption per Capita
        machine_name: consumption_pc
        unit: Thousands $USD / Person / Year
        description: Global average GDP per capita
        format: "$#.##"
        location: topright
      - name: Total Consumption
        machine_name: consumption
        unit: Trillions $USD / Year
      - name: Damages
        machine_name: damage
        unit: Trillions $USD / Year
      - name: Total Emissions per Year
        machine_name: emissions_total
        unit: Gt of Carbon / 10 yr
        description: Projected path of annual future carbon emissions
        location: bottomright
      - name: Industrial Emissions
        machine_name: emissions_ind
        unit: Gt of Carbon
      - name: Total Carbon Emitted
        machine_name: carbon_emitted
        unit: Gt of Carbon
      - name: Capital Stock
        machine_name: capital
        unit: Trillions $USD
      - name: Utility Discounted
        machine_name: utility_d
      - name: Utility
        machine_name: utility
      - name: Social Cost of Carbon
        machine_name: scc
  - name: Emissions Controls
    options:
      - name: Abatement
        machine_name: abatement
        unit: Trillions $USD / Year
      - name: Emissions Control Rate
        machine_name: miu
      - name: Abatement Cost as a Percentage of Output
        machine_name: output_abate
      - name: Tax Rate
        machine_name: tax_rate
  - name: Carbon Cycle
    options:
      - name: Carbon Mass in Atmosphere
        machine_name: mass_atmosphere
        unit: Gt of Carbon
        description: The projected concentration of carbon in the atmosphere.
        location: bottomleft
      - name: Carbon Mass in Upper Oceans
        machine_name: mass_upper
        unit: Gt of Carbon
      - name: Carbon Mass in Lower Oceans
        machine_name: mass_lower
        unit: Gt of Carbon
      - name: Atmospheric Temperature Increase
        machine_name: temp_atmosphere
        unit: °C from 1900
        description: Projected increases in global average temperatures compared to pre-industrial temperatures
        location: topleft
      - name: Lower Ocean Temperature Increase
        machine_name: temp_lower
        unit: °C from 1900

parameter_help:
  t2xco2: >



