about: >
  This file describes all the numeric parameters for the model. All values
  are assumed to be floats unless otherwise specified, and have the given
  range and precision values.
  
  The order of sections in the interface is the same as the order that they
  are first listed here.


initial_help: >
  webDICE is a simulation tool designed to show how climate change might
  affect people now and in the future. It is based on the most widely-used
  model of the economy and the climate developed by Professor William Nordhaus,
  of Yale University. Researchers at the University of Chicago have developed
  a way for the model to run quickly, with an easy to use web-based interface.
  The interface allows you to modify the variables in the model to reflect
  your views about the economy and climate change.

  To run a simulation, click on the "make new run" button at the bottom of
  the page. The variables are set to the defaults based on our best guess
  of the correct values. Because these values reflect predictions about
  what will happen in the future, they only reflect one possibility. You
  can change the variables to reflect your views by moving the sliders.
  Running a simulation will let you see how the outcomes change. The most
  important variables can be found on the "Basic simulation" tab. You
  can modify most of the other variables in the model on the "Advanced" tab.

  The model has a number of additional features which you may find useful
  such as calculating the optimal carbon tax and running Monte Carlo
  simulations. They are described in more detail in our FAQ [link].

  We are continually working to improve the model and the interface. If
  you have suggestions, you can contact as at [email].

basic_help: >
  ## WebDICE Documentation [Small Version]

  This block of text is primarily to explain the rationale behind all
  the various parameters in WebDICE as well as explain more about the
  internal processes of the model.

  Here is the quadratic formula:

  <p>$$x = \frac{-b \pm \sqrt{b^2 - 4ac}}{2a}$$</p>
  <!-- The <p></p> tags are necessary for Markdown -->

  And here is the equation for the identity matrix:

  <p>$$I_{x,y} = \delta_{xy}$$</p>

  Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim
  veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex
  ea commodo consequat. Duis aute irure dolor in reprehenderit in
  voluptate velit esse cillum dolore eu fugiat nulla pariatur. 
  Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia
  deserunt mollit anim id est laborum.

  Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim
  veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea
  commodo consequat. Duis aute irure dolor in reprehenderit in voluptate
  velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint
  occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit
  anim id est laborum.

intermediate_help: >
  ## WebDICE Documentation [Medium Version]

  This block of text is primarily to explain the rationale behind all
  the various parameters in WebDICE as well as explain more about the
  internal processes of the model.

  Here is the quadratic formula:

  <p>$$x = \frac{-b \pm \sqrt{b^2 - 4ac}}{2a}$$</p>
  <!-- The <p></p> tags are necessary for Markdown -->

  And here is the equation for the identity matrix:

  <p>$$I_{x,y} = \delta_{xy}$$</p>

  Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim
  veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex
  ea commodo consequat. Duis aute irure dolor in reprehenderit in
  voluptate velit esse cillum dolore eu fugiat nulla pariatur. 
  Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia
  deserunt mollit anim id est laborum.

  Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim
  veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea
  commodo consequat. Duis aute irure dolor in reprehenderit in voluptate
  velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint
  occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit
  anim id est laborum.

advanced_help: >
  ## WebDICE Documentation [Large Version]
  
  This block of text is primarily to explain the rationale behind all
  the various parameters in WebDICE as well as explain more about the
  internal processes of the model.
  
  Here is the quadratic formula:
  
  <p>$$x = \frac{-b \pm \sqrt{b^2 - 4ac}}{2a}$$</p>
  <!-- The <p></p> tags are necessary for Markdown -->
  
  And here is the equation for the identity matrix:
  
  <p>$$I_{x,y} = \delta_{xy}$$</p>
  
  Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim
  veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex
  ea commodo consequat. Duis aute irure dolor in reprehenderit in
  voluptate velit esse cillum dolore eu fugiat nulla pariatur. 
  Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia
  deserunt mollit anim id est laborum.
  
  Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim
  veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea
  commodo consequat. Duis aute irure dolor in reprehenderit in voluptate
  velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint
  occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit
  anim id est laborum.

last_modified: 5 July 2012 

parameters:
  - name: Climate Sensitivity
    machine_name: t2xco2
    tab: Basic
    section: Model Parameters
    min: 1
    max: 7
    step: 0.5
    default: 3
    description: Temperature increase in °C from doubling of atmospheric CO2 
  - name: Exponent of the Damage Function
    machine_name: a3
    tab: Basic
    section: Harm from Climate Change
    min: 1
    max: 3
    step: 0.5
    default: 2
    description: Increase in harms from climate change due to an increase in temperatures
  - name: Harm from 2.5% Increase
    tab: Basic
    section: Harm from Climate Change
    machine_name: a2
    default: 0.0028 # 388
    min:  0.002
    max:  0.0035
    step: 0.0001
  - name: Technological Growth
    machine_name: dela
    tab: Basic
    section: Model Parameters
    min: 0.05
    max: 0.15
    step: 0.05
    default: 0.1
    description: Decline in the rate of growth in productivity over time
  - name: Energy Intensity of the Economy
    tab: Basic
    section: Model Parameters
    machine_name: dsig
    default: 0.003
    min: 0
    max: 0.06
    step: 0.001
    description: Rate of decline in energy use per $ of GDP
  - name: 2050
    tab: Basic
    machine_name: e2050
    section: Reduction in Emissions below 2005 in
    min: 0.00
    max: 1.00
    step: 0.10
    default: 0.00
    description: The mandated decrease in emissions by 2050 as a share of 2005 year emissions.
  - name: 2100
    tab: Basic
    machine_name: e2100
    section: Reduction in Emissions below 2005 in
    min: 0.00
    max: 1.00
    step: 0.10
    default: 0.00
    description: The mandated decrease in emissions by 2100 as a share of 2005 year emissions.
  - name: 2150
    tab: Basic
    machine_name: e2150
    section: Reduction in Emissions below 2005 in
    min: 0.00
    max: 1.00
    step: 0.10
    default: 0.00
    description: The mandated decrease in emissions by 2150 as a share of 2005 year emissions.
  - name: Marginal Cost of abatement
    tab: Advanced
    section: Abatement
    machine_name: expcost2
    default: 2.8
    min: 2
    max: 4
    step: 0.1
    description: Additional cost from more abatement
  - name: Reduction in Abatement costs
    tab: Advanced
    section: Abatement
    machine_name: gback
    default: 0.05
    min: 0
    max: 0.2
    step: 0.05
    description: Rate of decline in costs of reduction emissions
  - name: Cost of Replacing all Emissions
    tab: Advanced
    section: Abatement
    machine_name: backrat
    default: 2
    min: 0.5
    max: 4
    step: 0.5
    description: Change in cost of replacing all emissions in the future in $ per ton of CO2, relative to today’s cost
  - name: Max Population
    tab: Advanced
    section: Additional Parameters
    machine_name: popasym
    min: 8000
    max: 12000
    step: 200
    default: 8600
    description: Number, in millions, that the population grows asymptotically towards
  - name: Depreciation Rate
    tab: Advanced
    section: Additional Parameters
    machine_name: dk
    default: 0.1
    min: 0.08
    max: 0.2
    step: 0.01
    description: Rate of depreciation per year
  - name: Savings Rate
    tab: Advanced
    section: Additional Parameters
    machine_name: savings
    default: 0.2
    min: 0.15
    max: 0.25
    step: 0.05
    description: Savings are per year
  - name: Fossil Fuel Reserves
    tab: Advanced
    section: Additional Parameters
    machine_name: fosslim
    min: 6000
    max: 9000
    step: 500
    default: 6000
    description: Fossil fuels remaining, measured in CO2 emissions
  - name: Carbon Cycle
    tab: Advanced
    machine_name: oceanmodel
    section: Model Design 
    description: Oceanic model of carbon transfer
    values:
      - name: DICE
        machine_name: dice
      - name: Glotter
        machine_name: glotter
  - name: Damages Model
    tab: Advanced
    machine_name: damages_model
    section: Model Design
    description: Way that climate change harms enter the economy
    values:
      - name: DICE Damages to Gross Output
        machine_name: dice
        description: Climate change destroys a certain percentage of global output
      - name: Kopp Damages to Capital
        machine_name: kopp
        description: Climate change destroys a certain percentage of global input
      - name: Damages to Productivity
        machine_name: productivity
        description: Climate change reduces the rate of growth in global productivity
  - name: Elasticity of Marginal Consumption
    tab: Optimization
    section: Additional Parameters
    machine_name: elasmu
    min: 1
    default: 2
    max: 3
    step: 0.1
    description: Exponent of consumption in utility function
  - name: Pure Rate of Time Preference
    tab: Optimization
    section: Additional Parameters
    machine_name: prstp
    min: 0
    default: 0.015
    max: 4
    step: 0.005
    description: Discount rate applied to utility


measurements:
  - name: Income per Capita
    machine_name: consumptionpercapita
    unit: per Person
    description: Global average GDP per capita
    format: "$#.##"
    location: topright
  - name: Atmospheric Temperature Increase
    machine_name: tempAtmosphere
    unit: °C from 1900
    description: Projected increases in global average temperatures compared to pre-industrial temperatures
    location: topleft
  - name: Carbon Mass in Atmosphere
    machine_name: massAtmosphere
    unit: Gt of Carbon
    description: The projected concentration of carbon in the atmosphere.
    location: bottomleft
  - name: Total Emissions per Year
    machine_name: emissionsTotal
    unit: Gt Carbon / 10 yr
    description: Projected path of annual future carbon emissions
    location: bottomright
  - name: Industrial Emissions
    machine_name: emissionsIndustrial
    unit: Gt Carbon