about: >
  This file describes all the numeric parameters for the model. All values
  are assumed to be floats unless otherwise specified, and have the given
  range and precision values.
  
  The order of sections in the interface is the same as the order that they
  are first listed here.

last_modified: 13 July 2012 

parameters:
  - name: Climate Sensitivity
    machine_name: sensitivity
    section: Model Parameters
    min: 1
    max: 7
    step: 0.5
    default: 3
    description: n/a
  - name: Environment Damages
    machine_name: damages
    section: Model Parameters
    min: 1
    max: 3
    step: 0.5
    default: 2
    description: n/a
  - name: Population Growth
    machine_name: population
    section: Model Parameters
    min: 0.1
    max: 0.5
    step: 0.05
    default: 0.35
    description: n/a
  - name: Technology Growth
    machine_name: technology
    section: Model Parameters
    min: 0.05
    max: 0.15
    step: 0.05
    default: 0.1
    description: n/a
  - name: Emissions by 2050
    machine_name: e2050
    section: Carbon Controls
    min: 0.00
    max: 1.00
    step: 0.10
    default: 0.00
  - name: Emissions by 2100
    machine_name: e2100
    section: Carbon Controls
    min: 0.00
    max: 1.00
    step: 0.10
    default: 0.00
  - name: Emissions by 2150
    machine_name: e2150
    section: Carbon Controls
    min: 0.00
    max: 1.00
    step: 0.10
    default: 0.00
  - name: Oceanic Model
    machine_name: oceanmodel
    section: Model Design 
    values:
      - name: DICE
        machine_name: dice
      - name: Glotter
        machine_name: glotter
  - name: Damages
    machine_name: damages
    section: Model Design
    values:
      - name: DICE Damages to Gross Output
        machine_name: dice
      - name: Kopp Damages to Capital
        machine_name: kopp
      - name: Damages to Productivity
        machine_name: productivity