data = pd.DataFrame({
            'miu': miu,
            'sigma': sigma,
            'al': al,
            'gcost1': gcost1,
            'capital': capital,
            'output': output,
            'mass_atmosphere': mass_atmosphere,
            'mass_upper': mass_upper,
            'mass_lower': mass_lower,
            'temp_atmosphere': temp_atmosphere,
            'temp_lower': temp_lower,
            'investment': investment,
            'gross_output': np.zeros(self.tmax),
            'forcing': np.zeros(self.tmax),
            'emissions_ind': np.zeros(self.tmax),
            'emissions_total': np.zeros(self.tmax),
            'carbon_emitted': np.zeros(self.tmax),
            'participation': np.zeros(self.tmax),
            'participation_markup': np.zeros(self.tmax),
            'damage': np.zeros(self.tmax),
            'abatement': np.zeros(self.tmax),
            'consumption': np.zeros(self.tmax),
            'consumption_pc': np.zeros(self.tmax),
            'utility': np.zeros(self.tmax),
            'utility_d': np.zeros(self.tmax),
            'pref_fac': np.ones(self.tmax),
        })