about: >
  This file describes all the numeric parameters for the model. All values
  are assumed to be floats unless otherwise specified, and have the given
  range and precision values.

  Things should be pretty self-explanatory. basic_tabs and advanced_tabs
  contain the parameters for those two pages. measurements controls the
  graphing operations. parameter_help contains help text for each parameter.

  Watch your indentation if you modify this file. Also keep in mind that typos
  make the gods angry.


initial_help:
  index: >
      webDICE is a simulation tool designed to show how climate change might affect
      people living today and in the future. It is based in the most widely used
      model of the economy and the climate, the DICE model, developed by Professor
      William Nordhaus, of Yale University. webDICE allows you to run the DICE
      model quickly with an easy to use interface. You can change the key variables
      in the model to reflect your views about the economy and about climate change
      and run the model with these choices.

      The complete set of DICE variables can be found in the “Advanced” version.
      An abbreviated set of variables is available in the “Basic” version.

      The model has been developed by researchers at the University of Chicago
      supported by RDCEP. We are continually working to improve the model and the
      interface. If you have suggestions, contact us at
      <a href="mailto:info-rdcep@ci.uchicago.edu" target="_blank">info-rdcep@ci.uchicago.edu</a>.


  advanced: >
      To run a simulation click on the “Run Model” button at the bottom of the
      page. The variables are set to the defaults based on our best guess of the
      correct values. You can change the variables to reflect your views by moving
      the sliders. Running a simulation will let you see how the outcomes change.


  basic: >
      To run a simulation click on the “Run Model” button at the bottom of the
      page. The variables are set to the defaults based on our best guess of the
      correct values. You can change the variables to reflect your views by moving
      the sliders. Running a simulation will let you see how the outcomes change.


basic_tabs:
  - name: Policy
    sections:
      - name: Business as usual
        machine_name: default
        radio: true
      - name: Simulated carbon tax
        machine_name: carbon_tax
        radio: true
        min: 0
        max: 500
        default: 0
        step: 10
        precision: 0
        unit: '$/t'
        init_disabled: true
        parameters:
          - name: 2050
            machine_name: c2050
          - name: 2100
            machine_name: c2100
          - name: 2150
            machine_name: c2150
      - name: Simulated climate treaty
        machine_name: treaty
        radio: true
      - name: 'Limitations on emissions (as a percent of 2005 emissions)'
        min: 0
        max: 100
        step: 5
        default: 0
        precision: 0
        unit: '%'
        init_disabled: true
        parameters:
          - name: 2050
            machine_name: e2050
            description: The mandated decrease in emissions by 2050 as a share of 2005 year emissions.
            class: reverse
          - name: 2100
            machine_name: e2100
            description: The mandated decrease in emissions by 2100 as a share of 2005 year emissions.
            class: reverse
          - name: 2150
            machine_name: e2150
            description: The mandated decrease in emissions by 2150 as a share of 2005 year emissions.
            class: reverse
      - name: Participation
        min: 0
        max: 100
        step: 10
        default: 100
        precision: 0
        unit: '%'
        init_disabled: true
        parameters:
          - name: 2050
            machine_name: p2050
            description: Participation in the climate treaty by 2050.
          - name: 2100
            machine_name: p2100
            description: Participation in the climate treaty by 2100.
          - name: 2150
            machine_name: p2150
            description: Participation in the climate treaty by 2150.
      - name: Optimized policy
        machine_name: optimized
        radio: true
  - name: Beliefs
    sections:
      - name: Your beliefs about the climate and the future
        min: 1
        max: 5
        default: 3
        step: 1
        precision: 0
        parameters:
          - name: 'Climate sensitivity: How much will temperatures go up?'
            machine_name: t2xco2
            description: Temperature increase in degrees C from doubling of atmospheric CO2
            unit: °C
            min_legend: Less than expected
            max_legend: More than expected
          - name: How large will the harms be?
            machine_name: a3
            description: Increase in harms from climate change due to an increase in temperatures
            min_legend: Less harm
            max_legend: More harm
          - name: Decline in rate of growth of productivity
            machine_name: dela
            description: Decline in the rate of growth in productivity over time
            min_legend: Slower growth
            max_legend: Faster growth
          - name: Change in energy efficiency
            machine_name: dsig
            description: Rate of decline in energy use per $ of GDP
            min_legend: Less energy efficient
            max_legend: More energy efficient
          - name: How low will the costs of renewables go?
            machine_name: backrat
            description: Cost of replacing all emissions in 2012 $ per ton of CO_{2} , relative to future cost
            min_legend: Less expensive
            max_legend: More expensive


advanced_tabs:
  - name: Policy
    sections:
      - name: Business as usual
        machine_name: default
        radio: true
      - name: Simulated carbon tax
        machine_name: carbon_tax
        radio: true
        min: 0
        max: 500
        default: 0
        step: 10
        precision: 0
        unit: '$/t'
        init_disabled: true
        parameters:
          - name: 2050
            machine_name: c2050
          - name: 2100
            machine_name: c2100
          - name: 2150
            machine_name: c2150
      - name: Simulated climate treaty
        machine_name: treaty
        radio: true
      - name: 'Limitations on emissions (as a percent of 2005 emissions)'
        min: 0
        max: 100
        step: 5
        default: 0
        precision: 0
        unit: '%'
        init_disabled: true
        parameters:
          - name: 2050
            machine_name: e2050
            description: The mandated decrease in emissions by 2050 as a share of 2005 year emissions.
            class: reverse
          - name: 2100
            machine_name: e2100
            description: The mandated decrease in emissions by 2100 as a share of 2005 year emissions.
            class: reverse
          - name: 2150
            machine_name: e2150
            description: The mandated decrease in emissions by 2150 as a share of 2005 year emissions.
            class: reverse
      - name: Participation
        min: 0
        max: 100
        step: 10
        default: 100
        precision: 0
        unit: '%'
        init_disabled: true
        parameters:
          - name: 2050
            machine_name: p2050
            description: Participation in the climate treaty by 2050.
          - name: 2100
            machine_name: p2100
            description: Participation in the climate treaty by 2100.
          - name: 2150
            machine_name: p2150
            description: Participation in the climate treaty by 2150.
      - name: Optimized policy
        machine_name: optimized
        radio: true
  - name: Climate
    sections:
      - name: Your beliefs about the climate and the future
        parameters:
          - name: 'Climate sensitivity: How much will temperatures go up?'
            machine_name: t2xco2
            min: 1
            max: 5
            step: 0.5
            default: 3.0
            precision: 1
            description: Temperature increase in degrees C from doubling of atmospheric CO2
            unit: °C
          - name: How large will the harms be?
            machine_name: a3
            min: 1
            max: 4
            step: 0.5
            default: 2.0
            precision: 1
            description: Increase in harms from climate change due to an increase in temperatures
      - name: Model design
        parameters:
          - name: Carbon cycle
            machine_name: carbon_model
            description: Oceanic model of carbon transfer
            disabled: true
            options:
              - name: DICE
                machine_name: dice_carbon
          - name: Damages model
            machine_name: damages_model
            description: Way that climate change harms enter the economy
            options:
              - name: DICE damages to output
                machine_name: dice_output
              - name: Exponential mapping to output
                machine_name: exponential_map
              - name: Additive to output
                machine_name: additive_output
              - name: Weitzman tipping point
                machine_name: tipping_point
              - name: Fraction of productivity
                machine_name: productivity_fraction
        #      - name: Kopp Damages to Capital
        #        machine_name: kopp
        #        description: Climate change destroys a certain percentage of global input
        #      - name: Damages to Productivity
        #        machine_name: productivity
        #        description: Climate change reduces the rate of growth in global productivity
          - name: Fraction of damages to productivity
            machine_name: prod_frac
            min: 0
            max: .25
            step: .05
            precision: 2
            default: .05
            init_disabled: true
  - name: Economy
    sections:
      - name: Cost of reducing emissions
        parameters:
          - name: Marginal cost of reducing emissions
            machine_name: expcost2
            default: 2.8
            min: 2
            max: 4
            step: 0.1
            precision: 1
            description: Additional cost from more abatement
          - name: How fast will the costs of renewable energy decline?
            machine_name: gback
            default: 0.05
            min: 0
            max: 0.2
            step: 0.05
            precision: 2
            description: Rate of decline in costs of reduction emissions
            unit: "%"
          - name: How low will the costs of renewables go?
            machine_name: backrat
            default: 2.0
            min: 1.0
            max: 4
            step: 0.5
            precision: 1
            description: Cost of replacing all emissions in 2012 $ per ton of CO_{2} , relative to future cost
      - name: Econommic performance
        parameters:
          - name: Decline in rate of growth of productivity
            machine_name: dela
            min: 0.05
            max: 1.5
            step: 0.05
            default: 0.10
            precision: 2
            description: Decline in the rate of growth in productivity over time
            unit: '%'
          - name: Depreciation rate
            machine_name: dk
            default: 0.10
            min: 0.08
            max: 0.2
            step: 0.01
            precision: 2
            description: Rate of depreciation per year
            unit: '%'
          - name: Savings rate
            machine_name: savings
            default: 0.2
            min: 0.15
            max: 0.25
            step: 0.05
            precision: 2
            description: Savings are per year
            unit: '%'
          - name: Max population
            tab: Advanced
            section: Additional Parameters
            machine_name: popasym
            min: 8000
            max: 12000
            step: 200
            default: 8600
            precision: 0
            description: Number, in millions, that the population grows asymptotically towards
            unit: ' billions'
      - name: Energy parameters
        parameters:
          - name: Reduction in energy intensity per decade
            machine_name: dsig
            default: 0.3
            min: 0.0
            max: 6.0
            step: 0.1
            precision: 1
            description: Rate of decline in energy use per $ of GDP
            unit: '%'
          - name: Fossil fuel reserves
            tab: Advanced
            section: Additional Parameters
            machine_name: fosslim
            min: 6000
            max: 9000
            step: 500
            default: 6000
            precision: 0
            description: Fossil fuels remaining, measured in CO2 emissions
            unit: ' Gt&nbsp;C'
      - name: Utility parameters
        parameters:
          - name: Elasticity of marg. consump.
            machine_name: elasmu
            min: 1
            default: 2.0
            max: 3
            step: 0.1
            precision: 1
            description: Exponent of consumption in utility function
          - name: Pure rate of time preference
            machine_name: prstp
            min: 0
            default: 0.015
            max: .1
            step: 0.005
            precision: 3
            description: Discount rate applied to utility


measurements:
  - name: User-controlled Inputs
    options:
      - name: Total Factor Productivity
        machine_name: al
      - name: Clean Energy Costs
        machine_name: backstop
        unit: Thousands $USD / ton of CO2
      - name: Carbon Intensity
        machine_name: sigma
        unit: tons of CO2 / 1000 $USD
      - name: Labor Supply
        machine_name: l
        unit: Millions
  - name: Economic Results
    options:
      - name: Consumption per Capita
        machine_name: consumption_pc
        unit: Thousands $USD / Person / Year
        description: Global average GDP per capita
        format: "$#.##"
        graphs:
          - name: essential
            location: topright
      - name: Total Consumption
        machine_name: consumption
        unit: Trillions $USD / Year
        graphs:
          - name: economy
            location: topright
      - name: Damages
        machine_name: damage
        unit: Trillions $USD / Year
        graphs:
          - name: economy
            location: topleft
      - name: Total Emissions per Year
        machine_name: emissions_total
        unit: Gt of Carbon / 10 yr
        description: Projected path of annual future carbon emissions
        graphs:
          - name: essential
            location: bottomright
      - name: Industrial Emissions
        machine_name: emissions_ind
        unit: Gt of Carbon
      - name: Total Carbon Emitted
        machine_name: carbon_emitted
        unit: Gt of Carbon
      - name: Capital Stock
        machine_name: capital
        unit: Trillions $USD
        graphs:
          - name: economy
            location: bottomleft
      - name: Utility Discounted
        machine_name: utility_d
      - name: Utility
        machine_name: utility
        graphs:
          - name: economy
            location: bottomright
      - name: Social Cost of Carbon
        machine_name: scc
        unit: '$'
  - name: Emissions Controls
    options:
      - name: Abatement
        machine_name: abatement
        unit: Trillions $USD / Year
      - name: Emissions Control Rate
        machine_name: miu
      - name: Abatement Cost as a Percentage of Output
        machine_name: output_abate
      - name: Tax Rate
        machine_name: tax_rate
  - name: Carbon Cycle
    options:
      - name: Carbon Mass in Atmosphere
        machine_name: mass_atmosphere
        unit: Gt of Carbon
        description: The projected concentration of carbon in the atmosphere.
        graphs:
          - name: essential
            location: bottomleft
      - name: Carbon Mass in Upper Oceans
        machine_name: mass_upper
        unit: Gt of Carbon
        graphs:
          - name: climate
            location: topleft
      - name: Carbon Mass in Lower Oceans
        machine_name: mass_lower
        unit: Gt of Carbon
        graphs:
          - name: climate
            location: topright
      - name: Atmospheric Temperature Increase
        machine_name: temp_atmosphere
        unit: °C from 1900
        description: Projected increases in global average temperatures compared to pre-industrial temperatures
        graphs:
          - name: essential
            location: topleft
      - name: Lower Ocean Temperature Increase
        machine_name: temp_lower
        unit: °C from 1900
        graphs:
          - name: climate
            location: bottomright

parameter_help:
  t2xco2: >
      TKTK


